# Generated by Django 5.0.6 on 2024-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WorkoutPlanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="name",
            field=models.CharField(default="Workout", max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
