# Generated by Django 5.0.6 on 2024-07-10 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WorkoutPlanner", "0002_workout_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="name",
        ),
    ]
