# Generated by Django 5.0.6 on 2024-07-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WorkoutPlanner", "0003_remove_workout_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
