# Generated by Django 5.0.6 on 2024-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WorkoutPlanner", "0004_workout_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutrecord",
            name="isCompleted",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="WorkoutCalendarEntry",
        ),
    ]
