# .github/workflows/docs.yml

name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # The branch you are using for development
  pull_request:
    branches:
      - main  # The branch you are using for development

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build documentation
        run: |
          sphinx-build -b html docs/source docs/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: docs/build
          publish_branch: gh-pages
